<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Validation\asTeaEvent\**" />
    <EmbeddedResource Remove="Validation\asTeaEvent\**" />
    <None Remove="Validation\asTeaEvent\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KulturPlatform.Domain\KulturPlatform.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\TeamMember\" />
    <Folder Include="Interfaces\TeamMember\" />
    <Folder Include="Queries\TeamMember\" />
    <Folder Include="Validation\AboutUs\" />
  </ItemGroup>

</Project>
