// <auto-generated />
using System;
using KulturPlatform.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KulturPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215092749_AddDeletedAtToAuditableEntity")]
    partial class AddDeletedAtToAuditableEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KulturPlatform.Domain.Commons.AggregateRoot.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailedContentDe")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("DetailedContentTr")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("User");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.ContactInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OfficeHours")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContactInfos", (string)null);
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.DonatePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContentGerman")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ContentTurkish")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DonatePages", (string)null);
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.GuelenMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentGerman")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ContentTurkish")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GuelenMovements", (string)null);
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.Imprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentResponsibilityGerman")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContentResponsibilityTurkish")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CopyrightGerman")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CopyrightTurkish")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LegalStructureGerman")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LegalStructureTurkish")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LinksResponsibilityGerman")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LinksResponsibilityTurkish")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrganizationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PurposeGerman")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PurposeTurkish")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TaxExemptionGerman")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TaxExemptionTurkish")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Imprints", (string)null);
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.LocalizationResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("English")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("German")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Turkish")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_LocalizationResources_IsActive");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_LocalizationResources_Key");

                    b.HasIndex("Section")
                        .HasDatabaseName("IX_LocalizationResources_Section");

                    b.ToTable("LocalizationResources", (string)null);
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.PageContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PageContents", (string)null);
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Partners", (string)null);
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.Satzung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentGerman")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentTurkish")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Satzungs", (string)null);
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.TeaEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionGerman")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DescriptionTurkish")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TeaEvents", (string)null);
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers", (string)null);
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.ValueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ValueItems", (string)null);
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.VolunteerSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VolunteerSubmissions", (string)null);
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.AggregateRoot.Activity", b =>
                {
                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Category", "Category", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Category");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.ActivityDate", "DateDe", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DateDe")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("DateDe_TextDe");

                            b1.Property<DateTime>("DateISO")
                                .HasColumnType("datetime2")
                                .HasColumnName("DateDe_DateISO");

                            b1.Property<string>("DateTr")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("DateDe_TextTr");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.ActivityDate", "DateTr", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DateDe")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("DateTr_TextDe");

                            b1.Property<DateTime>("DateISO")
                                .HasColumnType("datetime2")
                                .HasColumnName("DateTr_DateISO");

                            b1.Property<string>("DateTr")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("DateTr_TextTr");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Description", "DescriptionDe", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("DescriptionDe");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Description", "DescriptionTr", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("DescriptionTr");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Url", "ImageUrl", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("ImageUrl");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Location_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Location_Country");

                            b1.Property<string>("HouseNo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Location_State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Location_Address");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Location_ZipCode");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "TitleDe", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleDe");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "TitleTr", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleTr");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Url", "VideoUrl", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("VideoUrl");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.MediaGallery", "GalleryImages", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");

                            b1.OwnsMany("KulturPlatform.Domain.Commons.ValueObjects.Url", "Images", b2 =>
                                {
                                    b2.Property<Guid>("ActivityId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("nvarchar(500)")
                                        .HasColumnName("ImageUrl");

                                    b2.HasKey("ActivityId", "Id");

                                    b2.ToTable("ActivityGalleryImages", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ActivityId");
                                });

                            b1.Navigation("Images");
                        });

                    b.Navigation("Category")
                        .IsRequired();

                    b.Navigation("DateDe")
                        .IsRequired();

                    b.Navigation("DateTr")
                        .IsRequired();

                    b.Navigation("DescriptionDe")
                        .IsRequired();

                    b.Navigation("DescriptionTr")
                        .IsRequired();

                    b.Navigation("GalleryImages")
                        .IsRequired();

                    b.Navigation("ImageUrl");

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("TitleDe")
                        .IsRequired();

                    b.Navigation("TitleTr")
                        .IsRequired();

                    b.Navigation("VideoUrl");
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.Admin", b =>
                {
                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("AdminId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("AdminId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Admins");

                            b1.WithOwner()
                                .HasForeignKey("AdminId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("AdminId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("AdminId");

                            b1.ToTable("Admins");

                            b1.WithOwner()
                                .HasForeignKey("AdminId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("AdminId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("AdminId");

                            b1.ToTable("Admins");

                            b1.WithOwner()
                                .HasForeignKey("AdminId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.ContactInfo", b =>
                {
                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Location", "Address", b1 =>
                        {
                            b1.Property<Guid>("ContactInfoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Location_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Location_Country");

                            b1.Property<string>("HouseNo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Location_State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Location_Address");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Location_ZipCode");

                            b1.HasKey("ContactInfoId");

                            b1.ToTable("ContactInfos");

                            b1.WithOwner()
                                .HasForeignKey("ContactInfoId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.SocialMediaLinks", "SocialMedia", b1 =>
                        {
                            b1.Property<Guid>("ContactInfoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Facebook")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Facebook");

                            b1.Property<string>("Instagram")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Instagram");

                            b1.Property<string>("Twitter")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Twitter");

                            b1.HasKey("ContactInfoId");

                            b1.ToTable("ContactInfos");

                            b1.WithOwner()
                                .HasForeignKey("ContactInfoId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("SocialMedia")
                        .IsRequired();
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.Course", b =>
                {
                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Category", "CourseCategory", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CourseCategory");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Location", "CourseLocation", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CourseLocation_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CourseLocation_Country");

                            b1.Property<string>("HouseNo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CourseLocation_State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CourseLocation_Address");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("CourseLocation_ZipCode");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Description", "DescriptionDe", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("DescriptionDe");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Description", "DescriptionTr", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("DescriptionTr");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.CourseDetails", "DetailsDe", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("DetailsDe");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.CourseDetails", "DetailsTr", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("DetailsTr");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.CourseSchedule", "ScheduleDe", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("ScheduleDe");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.CourseSchedule", "ScheduleTr", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("ScheduleTr");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "TitleDe", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleDe");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "TitleTr", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleTr");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.InstructorName", "Instructor", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Instructor");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.Navigation("CourseCategory");

                    b.Navigation("CourseLocation");

                    b.Navigation("DescriptionDe")
                        .IsRequired();

                    b.Navigation("DescriptionTr")
                        .IsRequired();

                    b.Navigation("DetailsDe");

                    b.Navigation("DetailsTr");

                    b.Navigation("Instructor");

                    b.Navigation("ScheduleDe");

                    b.Navigation("ScheduleTr");

                    b.Navigation("TitleDe")
                        .IsRequired();

                    b.Navigation("TitleTr")
                        .IsRequired();
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.DonatePage", b =>
                {
                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Url", "HeroImageUrl", b1 =>
                        {
                            b1.Property<Guid>("DonatePageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("HeroImageUrl");

                            b1.HasKey("DonatePageId");

                            b1.ToTable("DonatePages");

                            b1.WithOwner()
                                .HasForeignKey("DonatePageId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "HeroSubtitleGerman", b1 =>
                        {
                            b1.Property<Guid>("DonatePageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("HeroSubtitleGerman");

                            b1.HasKey("DonatePageId");

                            b1.ToTable("DonatePages");

                            b1.WithOwner()
                                .HasForeignKey("DonatePageId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "HeroSubtitleTurkish", b1 =>
                        {
                            b1.Property<Guid>("DonatePageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("HeroSubtitleTurkish");

                            b1.HasKey("DonatePageId");

                            b1.ToTable("DonatePages");

                            b1.WithOwner()
                                .HasForeignKey("DonatePageId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "HeroTitleGerman", b1 =>
                        {
                            b1.Property<Guid>("DonatePageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("HeroTitleGerman");

                            b1.HasKey("DonatePageId");

                            b1.ToTable("DonatePages");

                            b1.WithOwner()
                                .HasForeignKey("DonatePageId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "HeroTitleTurkish", b1 =>
                        {
                            b1.Property<Guid>("DonatePageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("HeroTitleTurkish");

                            b1.HasKey("DonatePageId");

                            b1.ToTable("DonatePages");

                            b1.WithOwner()
                                .HasForeignKey("DonatePageId");
                        });

                    b.Navigation("HeroImageUrl")
                        .IsRequired();

                    b.Navigation("HeroSubtitleGerman")
                        .IsRequired();

                    b.Navigation("HeroSubtitleTurkish")
                        .IsRequired();

                    b.Navigation("HeroTitleGerman")
                        .IsRequired();

                    b.Navigation("HeroTitleTurkish")
                        .IsRequired();
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.GuelenMovement", b =>
                {
                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Url", "ImageUrl", b1 =>
                        {
                            b1.Property<Guid>("GuelenMovementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("ImageUrl");

                            b1.HasKey("GuelenMovementId");

                            b1.ToTable("GuelenMovements");

                            b1.WithOwner()
                                .HasForeignKey("GuelenMovementId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "TitleGerman", b1 =>
                        {
                            b1.Property<Guid>("GuelenMovementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleGerman");

                            b1.HasKey("GuelenMovementId");

                            b1.ToTable("GuelenMovements");

                            b1.WithOwner()
                                .HasForeignKey("GuelenMovementId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "TitleTurkish", b1 =>
                        {
                            b1.Property<Guid>("GuelenMovementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleTurkish");

                            b1.HasKey("GuelenMovementId");

                            b1.ToTable("GuelenMovements");

                            b1.WithOwner()
                                .HasForeignKey("GuelenMovementId");
                        });

                    b.Navigation("ImageUrl")
                        .IsRequired();

                    b.Navigation("TitleGerman")
                        .IsRequired();

                    b.Navigation("TitleTurkish")
                        .IsRequired();
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.Imprint", b =>
                {
                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Location", "Address", b1 =>
                        {
                            b1.Property<Guid>("ImprintId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Country");

                            b1.Property<string>("HouseNo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("PostalCode");

                            b1.HasKey("ImprintId");

                            b1.ToTable("Imprints");

                            b1.WithOwner()
                                .HasForeignKey("ImprintId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ImprintId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Email");

                            b1.HasKey("ImprintId");

                            b1.ToTable("Imprints");

                            b1.WithOwner()
                                .HasForeignKey("ImprintId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("ImprintId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Phone");

                            b1.HasKey("ImprintId");

                            b1.ToTable("Imprints");

                            b1.WithOwner()
                                .HasForeignKey("ImprintId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Name", "President", b1 =>
                        {
                            b1.Property<Guid>("ImprintId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("President");

                            b1.HasKey("ImprintId");

                            b1.ToTable("Imprints");

                            b1.WithOwner()
                                .HasForeignKey("ImprintId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Name", "VicePresident", b1 =>
                        {
                            b1.Property<Guid>("ImprintId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("VicePresident");

                            b1.HasKey("ImprintId");

                            b1.ToTable("Imprints");

                            b1.WithOwner()
                                .HasForeignKey("ImprintId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("President")
                        .IsRequired();

                    b.Navigation("VicePresident")
                        .IsRequired();
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.PageContent", b =>
                {
                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.LocalizedContent", "ContentDe", b1 =>
                        {
                            b1.Property<Guid>("PageContentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("ContentDe");

                            b1.HasKey("PageContentId");

                            b1.ToTable("PageContents");

                            b1.WithOwner()
                                .HasForeignKey("PageContentId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.LocalizedContent", "ContentTr", b1 =>
                        {
                            b1.Property<Guid>("PageContentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("ContentTr");

                            b1.HasKey("PageContentId");

                            b1.ToTable("PageContents");

                            b1.WithOwner()
                                .HasForeignKey("PageContentId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.PageName", "PageName", b1 =>
                        {
                            b1.Property<Guid>("PageContentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PageName");

                            b1.HasKey("PageContentId");

                            b1.ToTable("PageContents");

                            b1.WithOwner()
                                .HasForeignKey("PageContentId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.SectionKey", "SectionKey", b1 =>
                        {
                            b1.Property<Guid>("PageContentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("SectionKey");

                            b1.HasKey("PageContentId");

                            b1.ToTable("PageContents");

                            b1.WithOwner()
                                .HasForeignKey("PageContentId");
                        });

                    b.Navigation("ContentDe")
                        .IsRequired();

                    b.Navigation("ContentTr")
                        .IsRequired();

                    b.Navigation("PageName")
                        .IsRequired();

                    b.Navigation("SectionKey")
                        .IsRequired();
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.Partner", b =>
                {
                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.DisplayOrder", "DisplayOrder", b1 =>
                        {
                            b1.Property<Guid>("PartnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("DisplayOrder");

                            b1.HasKey("PartnerId");

                            b1.ToTable("Partners");

                            b1.WithOwner()
                                .HasForeignKey("PartnerId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Url", "LogoUrl", b1 =>
                        {
                            b1.Property<Guid>("PartnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("LogoUrl");

                            b1.HasKey("PartnerId");

                            b1.ToTable("Partners");

                            b1.WithOwner()
                                .HasForeignKey("PartnerId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Url", "WebsiteUrl", b1 =>
                        {
                            b1.Property<Guid>("PartnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("WebsiteUrl");

                            b1.HasKey("PartnerId");

                            b1.ToTable("Partners");

                            b1.WithOwner()
                                .HasForeignKey("PartnerId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.PartnerName", "Name", b1 =>
                        {
                            b1.Property<Guid>("PartnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Name");

                            b1.HasKey("PartnerId");

                            b1.ToTable("Partners");

                            b1.WithOwner()
                                .HasForeignKey("PartnerId");
                        });

                    b.Navigation("DisplayOrder")
                        .IsRequired();

                    b.Navigation("LogoUrl");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("WebsiteUrl");
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.Satzung", b =>
                {
                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "TitleGerman", b1 =>
                        {
                            b1.Property<Guid>("SatzungId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("TitleGerman");

                            b1.HasKey("SatzungId");

                            b1.ToTable("Satzungs");

                            b1.WithOwner()
                                .HasForeignKey("SatzungId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "TitleTurkish", b1 =>
                        {
                            b1.Property<Guid>("SatzungId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("TitleTurkish");

                            b1.HasKey("SatzungId");

                            b1.ToTable("Satzungs");

                            b1.WithOwner()
                                .HasForeignKey("SatzungId");
                        });

                    b.Navigation("TitleGerman")
                        .IsRequired();

                    b.Navigation("TitleTurkish")
                        .IsRequired();
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.TeaEvent", b =>
                {
                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Url", "ImageUrl", b1 =>
                        {
                            b1.Property<Guid>("TeaEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("ImageUrl");

                            b1.HasKey("TeaEventId");

                            b1.ToTable("TeaEvents");

                            b1.WithOwner()
                                .HasForeignKey("TeaEventId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("TeaEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Location_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Location_Country");

                            b1.Property<string>("HouseNo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Location_State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Location_Address");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Location_ZipCode");

                            b1.HasKey("TeaEventId");

                            b1.ToTable("TeaEvents");

                            b1.WithOwner()
                                .HasForeignKey("TeaEventId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "TitleGerman", b1 =>
                        {
                            b1.Property<Guid>("TeaEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleGerman");

                            b1.HasKey("TeaEventId");

                            b1.ToTable("TeaEvents");

                            b1.WithOwner()
                                .HasForeignKey("TeaEventId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "TitleTurkish", b1 =>
                        {
                            b1.Property<Guid>("TeaEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleTurkish");

                            b1.HasKey("TeaEventId");

                            b1.ToTable("TeaEvents");

                            b1.WithOwner()
                                .HasForeignKey("TeaEventId");
                        });

                    b.Navigation("ImageUrl")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("TitleGerman")
                        .IsRequired();

                    b.Navigation("TitleTurkish")
                        .IsRequired();
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.TeamMember", b =>
                {
                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.LocalizedText", "BioDe", b1 =>
                        {
                            b1.Property<Guid>("TeamMemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("BioDe_De");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("BioDe_Tr");

                            b1.HasKey("TeamMemberId");

                            b1.ToTable("TeamMembers");

                            b1.WithOwner()
                                .HasForeignKey("TeamMemberId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.LocalizedText", "BioTr", b1 =>
                        {
                            b1.Property<Guid>("TeamMemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("BioTr_De");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("BioTr_Tr");

                            b1.HasKey("TeamMemberId");

                            b1.ToTable("TeamMembers");

                            b1.WithOwner()
                                .HasForeignKey("TeamMemberId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.DisplayOrder", "DisplayOrder", b1 =>
                        {
                            b1.Property<Guid>("TeamMemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("DisplayOrder");

                            b1.HasKey("TeamMemberId");

                            b1.ToTable("TeamMembers");

                            b1.WithOwner()
                                .HasForeignKey("TeamMemberId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Url", "ImageUrl", b1 =>
                        {
                            b1.Property<Guid>("TeamMemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("ImageUrl");

                            b1.HasKey("TeamMemberId");

                            b1.ToTable("TeamMembers");

                            b1.WithOwner()
                                .HasForeignKey("TeamMemberId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("TeamMemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Name");

                            b1.HasKey("TeamMemberId");

                            b1.ToTable("TeamMembers");

                            b1.WithOwner()
                                .HasForeignKey("TeamMemberId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.LocalizedText", "RoleDe", b1 =>
                        {
                            b1.Property<Guid>("TeamMemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("RoleDe_De");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("RoleDe_Tr");

                            b1.HasKey("TeamMemberId");

                            b1.ToTable("TeamMembers");

                            b1.WithOwner()
                                .HasForeignKey("TeamMemberId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.LocalizedText", "RoleTr", b1 =>
                        {
                            b1.Property<Guid>("TeamMemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("RoleTr_De");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("RoleTr_Tr");

                            b1.HasKey("TeamMemberId");

                            b1.ToTable("TeamMembers");

                            b1.WithOwner()
                                .HasForeignKey("TeamMemberId");
                        });

                    b.Navigation("BioDe")
                        .IsRequired();

                    b.Navigation("BioTr")
                        .IsRequired();

                    b.Navigation("DisplayOrder")
                        .IsRequired();

                    b.Navigation("ImageUrl");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("RoleDe")
                        .IsRequired();

                    b.Navigation("RoleTr")
                        .IsRequired();
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.ValueItem", b =>
                {
                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Description", "DescriptionDe", b1 =>
                        {
                            b1.Property<Guid>("ValueItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("DescriptionDe");

                            b1.HasKey("ValueItemId");

                            b1.ToTable("ValueItems");

                            b1.WithOwner()
                                .HasForeignKey("ValueItemId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Description", "DescriptionTr", b1 =>
                        {
                            b1.Property<Guid>("ValueItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("DescriptionTr");

                            b1.HasKey("ValueItemId");

                            b1.ToTable("ValueItems");

                            b1.WithOwner()
                                .HasForeignKey("ValueItemId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.DisplayOrder", "DisplayOrder", b1 =>
                        {
                            b1.Property<Guid>("ValueItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("DisplayOrder");

                            b1.HasKey("ValueItemId");

                            b1.ToTable("ValueItems");

                            b1.WithOwner()
                                .HasForeignKey("ValueItemId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "TitleDe", b1 =>
                        {
                            b1.Property<Guid>("ValueItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleDe");

                            b1.HasKey("ValueItemId");

                            b1.ToTable("ValueItems");

                            b1.WithOwner()
                                .HasForeignKey("ValueItemId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Title", "TitleTr", b1 =>
                        {
                            b1.Property<Guid>("ValueItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleTr");

                            b1.HasKey("ValueItemId");

                            b1.ToTable("ValueItems");

                            b1.WithOwner()
                                .HasForeignKey("ValueItemId");
                        });

                    b.Navigation("DescriptionDe")
                        .IsRequired();

                    b.Navigation("DescriptionTr")
                        .IsRequired();

                    b.Navigation("DisplayOrder")
                        .IsRequired();

                    b.Navigation("TitleDe")
                        .IsRequired();

                    b.Navigation("TitleTr")
                        .IsRequired();
                });

            modelBuilder.Entity("KulturPlatform.Domain.Commons.Aggregates.VolunteerSubmission", b =>
                {
                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("VolunteerSubmissionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Email");

                            b1.HasKey("VolunteerSubmissionId");

                            b1.ToTable("VolunteerSubmissions");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerSubmissionId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.Name", "FullName", b1 =>
                        {
                            b1.Property<Guid>("VolunteerSubmissionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("FullName");

                            b1.HasKey("VolunteerSubmissionId");

                            b1.ToTable("VolunteerSubmissions");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerSubmissionId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("VolunteerSubmissionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("VolunteerSubmissionId");

                            b1.ToTable("VolunteerSubmissions");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerSubmissionId");
                        });

                    b.OwnsOne("KulturPlatform.Domain.Commons.ValueObjects.SubmissionMessage", "Message", b1 =>
                        {
                            b1.Property<Guid>("VolunteerSubmissionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("Message");

                            b1.HasKey("VolunteerSubmissionId");

                            b1.ToTable("VolunteerSubmissions");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerSubmissionId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("Message")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
